"""Compatibility exports; formatter implementation lives in .formatters."""

from .formatters import (
    PnsDecision,
    PnsPolicyConfig,
    PnsStateMachine,
    PnsSubtypeConfig,
    _aligned_table_rows,
    _as_tuple_strings,
    _build_script,
    _contains_all,
    _contains_any,
    _headline_lines,
    _match_subtype,
    _parse_dt,
    _sha1_12,
    _split_spoken_candidate,
    default_pns_subtypes,
    detect_computer_block_signals,
    parse_nws_header_issued_dt,
    parse_ugc_expiry_utc,
    pns_text_same_issuance,
    policy_from_config,
)

__all__ = [
    "PnsSubtypeConfig",
    "PnsPolicyConfig",
    "PnsDecision",
    "default_pns_subtypes",
    "_as_tuple_strings",
    "policy_from_config",
    "_parse_dt",
    "parse_nws_header_issued_dt",
    "pns_text_same_issuance",
    "parse_ugc_expiry_utc",
    "_split_spoken_candidate",
    "_headline_lines",
    "_contains_any",
    "_contains_all",
    "_aligned_table_rows",
    "detect_computer_block_signals",
    "_match_subtype",
    "_build_script",
    "_sha1_12",
    "PnsStateMachine",
]
