from importlib.metadata import PackageNotFoundError, version

try:
    # Generated by setuptools-scm during editable/wheel installs.
    from ._version import version as __version__
except ImportError:
    try:
        __version__ = version("seasonalweather")
    except PackageNotFoundError:
        # Uninstalled source checkouts retain a bounded development fallback;
        # controlled builds derive the authoritative package version from Git.
        __version__ = "0.17.0"
